### ISSUE TITLE
The automatic updating of menus is not working

### ISSUE THREAD

**Issue by Vaso64** [TomasZouhar/menu_from_url#6]
### Problem
The automatic daily updating feature for local restaurant menus is currently malfunctioning, rendering our beloved app's usability in jeopardy. As it stands, users are stuck with outdated menus, leading to potential chaos in their dining plans.

### Reproduction Steps
1. Open the app.
2. Navigate to any local restaurant's menu.
3. Observe that the menu doesn't reflect the latest offerings.
4. Wonder why your dinner plans are now a culinary wild guess.

### Expected Behavior
Menus should automatically update daily to provide users with the most accurate and mouth-watering choices from their favorite local eateries.

### Why This Matters
**Hangry Users**: Imagine a user relying on our app to decide their dinner plans. The frustration of finding out that their favorite dish is no longer available could lead to serious "hangriness."
**Dining Disasters**: Outdated menus might lead users to order items that are no longer available or miss out on exciting new additions.
### Code Owner, We Need to Talk 
@TomasZouhar, we've got a serious situation here! The automatic daily updating is as absent as a disappearing magician's rabbit. Our users are suffering menu-related woes, and it's high time we address this issue before the hangry revolution begins.

### Proposed Solution
Let's wave our magic coding wand and ensure that the daily menu updates work seamlessly. Investigate the code, squash those bugs, and let's make our users' dining experiences delightful again.

### Deadline
Given the urgency of the matter, let's aim to resolve this before our users start resorting to coin flips to decide their meals.

### Remember, Happy Stomachs, Happy Users!
This functionality is not just a nicety; it's the essence of our app. Let's get those menus updated daily and keep our users happily fed!

**Comment by TomasZouhar** [comment]
Who asked
